name: VCMI

on:
  push:
    branches:
      - beta
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.platform }})
    strategy:
      fail-fast: false      # Do not cancel whole matrix when one build fails
      matrix:
        include:
          - platform: android-64
            os: ubuntu-latest
            upload: 1
            extension: apk
            preset: android-conan-ninja-release
            conan_profile: android-64-ndk
            conan_prebuilts: dependencies-android-arm64-v8a
            conan_options: --profile=dependencies/conan_profiles/base/android-system
            artifact_platform: arm64-v8a

    runs-on: ${{ matrix.os }}
    # Allow non-MSVC builds to fail without failing whole job
    # This keeps pipeline moving so Windows Installer job can still run
    # MSVC builds must success to continue to Windows Installer job
    continue-on-error: ${{ !startsWith(matrix.platform, 'msvc') }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Prepare APT staging dir
      if: contains(matrix.os, 'ubuntu')
      run: mkdir -p "$RUNNER_TEMP/apt-cache"

    - name: APT cache restore
      if: contains(matrix.os, 'ubuntu')
      id: aptcache
      uses: actions/cache/restore@v4
      with:
        path: ${{ runner.temp }}/apt-cache
        key: ${{ matrix.platform }}-apt-${{ matrix.os }}
        restore-keys: |
          ${{ matrix.platform }}-apt-${{ matrix.os }}

    - name: Prepare CI
      if: "${{ matrix.before_install != '' }}"
      run: source '${{github.workspace}}/CI/before_install/${{matrix.before_install}}' '${{matrix.arch}}'

    # Save only on cache miss, GitHub caches are immutable per key
    - name: APT cache save
      if: contains(matrix.os, 'ubuntu') && steps.aptcache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ runner.temp }}/apt-cache
        key: ${{ steps.aptcache.outputs.cache-primary-key }}

    - name: Install Conan Dependencies
      if: "${{ matrix.conan_prebuilts != '' }}"
      run: |
        pipx install conan
        source '${{github.workspace}}/CI/install_conan_dependencies.sh' '${{matrix.conan_prebuilts}}'

    - name: Setup MSVC Developer Command Prompt
      if: ${{ startsWith(matrix.platform, 'msvc') }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
        toolset: ${{ matrix.toolset }}

    # ensure the cache for each PR is separate so they don't interfere with each other
    # fall back to cache of the vcmi/vcmi repo if no PR-specific cache is found

    - name: Setup compiler cache for PRs
      uses: hendrikmuhs/ccache-action@v1.2
      if: ${{ github.event.number != '' }}
      with:
        variant: ${{ startsWith(matrix.platform, 'msvc') && 'sccache' || 'ccache' }}
        key: ${{ matrix.platform }}-PR-${{ github.event.number }}
        restore-keys: |
          ${{ matrix.platform }}-PR-${{ github.event.number }}
          ${{ matrix.platform }}-branch-${{ github.base_ref }}
          ${{ matrix.platform }}-
        create-symlink: ${{ !startsWith(matrix.platform, 'msvc') }}
        max-size: '5G'
        verbose: 2
        job-summary: ""           # <-- disable built-in summary to avoid duplicate block

    - name: Setup compiler cache for branch builds
      uses: hendrikmuhs/ccache-action@v1.2
      if: ${{ github.event.number == '' }}
      with:
        variant: ${{ startsWith(matrix.platform, 'msvc') && 'sccache' || 'ccache' }}
        key: ${{ matrix.platform }}-branch-${{ github.ref_name }}
        restore-keys: |
          ${{ matrix.platform }}-branch-${{ github.ref_name }}
          ${{ matrix.platform }}-
        create-symlink: ${{ !startsWith(matrix.platform, 'msvc') }}
        max-size: '5G'
        verbose: 2
        job-summary: ""           # <-- disable built-in summary to avoid duplicate block

    - name: CCache tuning (Android)
      if: ${{ startsWith(matrix.platform, 'android') }}
      run: |
        echo "/usr/lib/ccache" >> $GITHUB_PATH
        ccache --set-config=compiler_check=content
        ccache --set-config=base_dir="${GITHUB_WORKSPACE}"
        ccache --set-config=hash_dir=true
        ccache --set-config=sloppiness=time_macros

    - name: Install Conan profile
      if: "${{ matrix.conan_profile != '' }}"
      run: |
        conan profile detect
        outFolder=conan-generated
        conan install . \
          --output-folder="$outFolder" \
          --build=never \
          --profile=dependencies/conan_profiles/${{ matrix.conan_profile }} \
          ${{ matrix.conan_options }}
        ${{ startsWith(matrix.platform, 'msvc') && 'echo CONANRUN_PWSH_SCRIPT="$outFolder/conanrun.ps1" >> $GITHUB_ENV' || '' }}

    # Can't be set in Gradle project
    - name: Configure enableUncompressedNativeLibs
      if: ${{ startsWith(matrix.platform, 'android') }}
      run: mkdir -p ~/.gradle && echo "android.bundle.enableUncompressedNativeLibs=true" > ~/.gradle/gradle.properties

    # Workaround for gradle not discovering SDK that was installed via Сonan
    - name: Link Android NDK from Conan cache to Android SDK path
      if: ${{ startsWith(matrix.platform, 'android') }}
      run: |
        ndkPackage='android-ndk'
        hexRegex='[[:xdigit:]]+'

        ndkPackageRevision=$(conan list "$ndkPackage/*:*" --format=compact \
          | egrep --only-matching "$ndkPackage/\\w+#$hexRegex:$hexRegex")
        ndkPackagePath=$(conan cache path "$ndkPackageRevision")

        # format: Pkg.Revision = 25.2.9519653
        ndkPath="$ndkPackagePath/bin"
        ndkVersion=$(fgrep 'Pkg.Revision' "$ndkPath/source.properties" | cut -d ' ' -f 3)
        ln -s -T "$ndkPath" "$ANDROID_HOME/ndk/$ndkVersion"

    - name: Install Java
      uses: actions/setup-java@v5
      if: ${{ startsWith(matrix.platform, 'android') }}
      with:
        distribution: 'temurin'
        java-version: '17'

    # a hack to build ID for x64 build in order for Google Play to allow upload of both 32 and 64 bit builds
    # TODO: x86_64
    - name: Bump Android x64 build ID
      if: ${{ matrix.platform == 'android-64' }}
      run: perl -i -pe 's/versionCode (\d+)/$x=$1+1; "versionCode $x"/e' android/vcmi-app/build.gradle

    - name: Build Number
      run: |
        source '${{github.workspace}}/CI/get_package_name.sh'
        if [ '${{ matrix.artifact_platform }}' ]; then
          VCMI_PACKAGE_FILE_NAME+="-${{ matrix.artifact_platform }}"
        fi
        echo VCMI_PACKAGE_FILE_NAME="$VCMI_PACKAGE_FILE_NAME" >> $GITHUB_ENV
        echo VCMI_PACKAGE_BUILD="$VCMI_PACKAGE_BUILD" >> $GITHUB_ENV
        echo VCMI_PACKAGE_NAME_SUFFIX="$VCMI_PACKAGE_NAME_SUFFIX" >> $GITHUB_ENV
        echo VCMI_PACKAGE_GOLDMASTER="$VCMI_PACKAGE_GOLDMASTER" >> $GITHUB_ENV
      env:
        PULL_REQUEST: ${{ github.event.pull_request.number }}

    - name: Configure (non-MSVC)
      if: ${{ !startsWith(matrix.platform, 'msvc') }}
      run: |
        if [[ ("${{ matrix.preset }}" == "android-conan-ninja-release") && ("${{ github.ref }}" != 'refs/heads/master') ]]; then
          # key1=value1;key2=value2;...
          gradleProperties=$(python3 CI/android/gradle_daily_props.py)
          androidOptions=("-DANDROID_GRADLE_PROPERTIES=$gradleProperties")
          androidOptions+=("-DCMAKE_C_COMPILER_LAUNCHER=ccache" "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache")
        fi
        cmake -DENABLE_CCACHE:BOOL=ON "${androidOptions[@]}" --preset ${{ matrix.preset }}
    - name: Configure (MSVC)
      if: ${{ startsWith(matrix.platform, 'msvc') }}
      run: |
        & $env:CONANRUN_PWSH_SCRIPT

        cmake --preset ${{ matrix.preset }}
      shell: pwsh

    - name: Build
      run: |
        ${{ startsWith(matrix.platform, 'msvc') && '& $env:CONANRUN_PWSH_SCRIPT' }}
        cmake --build --preset ${{matrix.preset}}
      shell: pwsh
      env:
        ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Kill XProtect to work around CPack issue on macOS
      if: ${{ startsWith(matrix.platform, 'mac') }}
      run: |
        # Cf. https://github.com/actions/runner-images/issues/7522#issuecomment-1556766641
        echo Killing...; sudo pkill -9 XProtect >/dev/null || true;
        echo "Waiting..."; counter=0; while pgrep XProtect && ((counter < 20)); do sleep 3; ((counter++)); done
        pgrep XProtect || true

    - name: Pack
      id: cpack
      if: ${{ matrix.pack == 1 }}
      run: |
        ${{ startsWith(matrix.platform, 'msvc') && '& $env:CONANRUN_PWSH_SCRIPT' }}
        cd "${{github.workspace}}/out/build/${{matrix.preset}}"
        cpack -C ${{matrix.pack_type}}
      shell: pwsh

    - name: Find Android package
      if: ${{ startsWith(matrix.platform, 'android') }}
      run: |
        OUTPUT_DIRECTORY="${{ github.workspace }}/out/build/${{ matrix.preset }}/android-build/vcmi-app/build/outputs"
        mv "$OUTPUT_DIRECTORY/apk/release/vcmi-release.apk" "${{github.workspace}}/out/build/${{matrix.preset}}/${{ env.VCMI_PACKAGE_FILE_NAME }}.apk"
        mv "$OUTPUT_DIRECTORY/bundle/release/vcmi-release.aab" "${{github.workspace}}/out/build/${{matrix.preset}}/${{ env.VCMI_PACKAGE_FILE_NAME }}.aab"

    - name: Upload Artifact
      id: upload_artifact
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.VCMI_PACKAGE_FILE_NAME }} - ${{ matrix.platform }}
        compression-level: 9
        path: |
          ${{github.workspace}}/out/build/${{matrix.preset}}/${{ env.VCMI_PACKAGE_FILE_NAME }}.${{ matrix.extension }}

    - name: Upload AAB Artifact
      id: upload_aab
      if: ${{ startsWith(matrix.platform, 'android') && github.ref == 'refs/heads/master' }}
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.VCMI_PACKAGE_FILE_NAME }} - ${{ matrix.platform }} - aab
        compression-level: 9
        path: |
          ${{github.workspace}}/out/build/${{matrix.preset}}/${{ env.VCMI_PACKAGE_FILE_NAME }}.aab

    - name: Upload debug symbols
      id: upload_symbols
      if: ${{ startsWith(matrix.platform, 'msvc') }}
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.VCMI_PACKAGE_FILE_NAME }} - ${{ matrix.platform }} - symbols
        compression-level: 9
        path: |
            ${{github.workspace}}/**/*.pdb

    - name: Upload build to download.vcmi.eu
      if: ${{ matrix.upload == 1 && github.event.number == '' && env.DEPLOY_RSA != '' }}
      run: |
        if [ -z '${{ env.ANDROID_APK_PATH }}' ] ; then
          cd '${{github.workspace}}/out/build/${{matrix.preset}}'
        fi
        source '${{github.workspace}}/CI/upload_package.sh'
      env:
        DEPLOY_RSA: ${{ secrets.DEPLOY_RSA }}
        PACKAGE_EXTENSION: ${{ matrix.extension }}

    - name: Prepare partial JSON with build informations
      id: make_partial_json
      env:
        PLATFORM: ${{ matrix.platform }}
        ARTIFACT_URL: ${{ steps.upload_artifact.outputs.artifact-url }}
        DEBUG_SYMBOLS_URL: ${{ steps.upload_symbols.outputs.artifact-url }}
        AAB_URL: ${{ steps.upload_aab.outputs.artifact-url }}
      run: |
        python3 CI/emit_partial.py

    - name: Upload partial JSON with build informations
      uses: actions/upload-artifact@v5
      with:
        name: partial-json-${{ matrix.platform }}
        path: .summary/${{ matrix.platform }}.json
